[package]
name = "schema"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "schema_parser_benchmark"
harness = false

[[bin]]
name = "schema_parser"
path = "src/bin/schema_parser.rs"

[dependencies]
nom = "7.1.3"
thiserror = "1.0.58"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
quaternion = "1.0.0"
